# Generated by Django 5.2.1 on 2025-06-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_app', '0004_qrbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrbooking',
            old_name='u_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='qrbooking',
            name='email',
            field=models.EmailField(default='dummy@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
