# Generated by Django 5.2.1 on 2025-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_app', '0005_rename_u_name_qrbooking_name_qrbooking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
