# Generated by Django 5.2.1 on 2025-06-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_app', '0006_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
