# Generated by Django 5.2.1 on 2025-06-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_app', '0007_event_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='domain',
            field=models.CharField(choices=[('technology', 'Technology'), ('art_culture', 'Art & Culture'), ('music', 'Music'), ('sports', 'Sports'), ('gaming', 'Gaming'), ('business', 'Business'), ('education', 'Education'), ('health_wellness', 'Health & Wellness'), ('food_drinks', 'Food & Drinks'), ('fashion', 'Fashion'), ('travel_adventure', 'Travel & Adventure')], default='Other', max_length=30),
        ),
    ]
