# Generated by Django 5.2.1 on 2025-06-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_app', '0008_event_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='booking_qr/'),
        ),
        migrations.AddField(
            model_name='qrbooking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='booking_qr/'),
        ),
    ]
