services:
  - type: web
    name: event-booking-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn event_booking_project.wsgi:application"
    pythonVersion: 3.12.3  # ⬅️ Use 3.12 or 3.11

